apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: ingress-ssl
  namespace: site
  annotations:
    kubernetes.io/ingress.class: "nginx"  # 사용 중인 Ingress 컨트롤러에 맞게 설정
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - newsum.click
    secretName: news-tls-secret
  rules:
  - host: newsum.click
    http:
      paths:
      - pathType: Prefix
        path: / 
        backend:
          service: 
            name: news-deploy
            port:
              number: 3000
